; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
;platform = https://github.com/platformio/platform-espressif32.git#v6.6.0
;platform_packages = framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.14

platform = https://github.com/platformio/platform-espressif32.git#v6.2.0  ; ESP-IDF v4.4.4
platform_packages = framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.8

framework = arduino, espidf
board_build.f_cpu = 240000000L
board_build.flash_freq = 80M
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 460800
;AVAILABLE: cmsis-dap, esp-bridge, esp-builtin, esp-prog, espota, (*)esptool, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa
board_build.arduino.upstream_packages = no
board_build.bootloader = dio

[env:woofer]
board = esp32-s3
board_build.spiram_mode = 2
board_build.flash_mode = qio
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
board_build.partitions = partitions.csv
upload_protocol = esptool
upload_port = COM4
monitor_port = COM4
build_flags = 
	-Wall
	-Wextra
	-DCORE_DEBUG_LEVEL=4
    ;-DCONFIG_ARDUHAL_LOG_COLORS=1
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_RUNNING_CORE=1
	-DARDUINO_EVENT_RUNNING_CORE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DSUPERWOOFER=1
lib_deps = 
	lovyan03/LovyanGFX@^1.1.12
	https://github.com/yellobyte/SoapESP32.git#1.1.4

[env:workradio]
board = esp32-s3
;board_build.spiram_mode = 2
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_qspi
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
board_build.partitions = partitions.csv
upload_protocol = esptool
upload_port = COM9
monitor_port = COM9
build_flags = 
	-Wall
	-Wextra
	-DCORE_DEBUG_LEVEL=4
    ;-DCONFIG_ARDUHAL_LOG_COLORS=1
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_RUNNING_CORE=1
	-DARDUINO_EVENT_RUNNING_CORE=1
	-DARDUINO_USB_CDC_ON_BOOT=0
	-DWORKRADIO=1
lib_deps = 
	lovyan03/LovyanGFX@^1.1.12
	https://github.com/yellobyte/SoapESP32.git#1.1.4


[env:workradio2]
board = esp32dev
board_build.boot = qio
board_build.flash_mode = qio
board_build.psram_type = qspi
board_build.arduino.memory_type = qio_qspi 
board_build.partitions = partitions4.csv
upload_protocol = esptool
upload_port = COM9
monitor_port = COM9
build_flags = 
	-Wall
	-Wextra
	-DCORE_DEBUG_LEVEL=4
    ;-DCONFIG_ARDUHAL_LOG_COLORS=1
	-DBOARD_HAS_PSRAM
	-DARDUINO_RUNNING_CORE=1
	-DARDUINO_EVENT_RUNNING_CORE=1
	-DWORKRADIO2=1
lib_deps = 
	lovyan03/LovyanGFX@^1.1.12
	https://github.com/yellobyte/SoapESP32.git#1.1.4
	;https://github.com/pschatzmann/ESP32-A2DP#v.1.8.1
	;https://github.com/pschatzmann/arduino-audio-tools.git#v0.9.8


[env:miniradio]
board = esp32dev
board_build.boot = qio
board_build.flash_mode = qio
board_build.psram_type = qspi
board_build.arduino.memory_type = qio_qspi 
board_build.partitions = partitions4ota.csv
;upload_protocol = esptool
;upload_port = COM9
upload_protocol = espota
upload_port = 192.168.0.52
upload_flags =
	--auth=admin
monitor_port = socket://deskradio.local:4444
build_flags = 
	-Wall
	-Wextra
	-DCORE_DEBUG_LEVEL=4
    ;-DCONFIG_ARDUHAL_LOG_COLORS=1
	-DBOARD_HAS_PSRAM
	-DARDUINO_RUNNING_CORE=1
	-DARDUINO_EVENT_RUNNING_CORE=1
	-DMINIRADIO=1
lib_deps = 
	lovyan03/LovyanGFX@^1.1.12
	https://github.com/yellobyte/SoapESP32.git#1.1.4
	;https://github.com/pschatzmann/ESP32-A2DP#v.1.8.1
	;https://github.com/pschatzmann/arduino-audio-tools.git#v0.9.8

[env:panasonic]
board = esp32dev
board_build.boot = qio
board_build.flash_mode = qio
board_build.psram_type = qspi
board_build.arduino.memory_type = qio_qspi 
board_build.partitions = partitions4.csv
upload_protocol = esptool
upload_port = COM7
monitor_port = COM7  ; Or /dev/ttyUSB0 for Linux/Mac
monitor_speed = 115200
;upload_protocol = espota
;upload_port = deskradio.local
;upload_flags =
;	--auth=admin
;monitor_port = socket://deskradio.local:4444
build_flags = 
	-Wall
	-Wextra
	-DCORE_DEBUG_LEVEL=4
    ;-DCONFIG_ARDUHAL_LOG_COLORS=1
	-DBOARD_HAS_PSRAM
	-DARDUINO_RUNNING_CORE=1
	-DARDUINO_EVENT_RUNNING_CORE=1
	-DPANASONIC=1
lib_deps = 
	lovyan03/LovyanGFX@^1.1.12
	https://github.com/yellobyte/SoapESP32.git#1.1.4
	;https://github.com/pschatzmann/ESP32-A2DP#v.1.8.1
	;https://github.com/pschatzmann/arduino-audio-tools.git#v0.9.8

[env:philips]
board = esp32dev
board_build.boot = qio
board_build.flash_mode = qio
board_build.psram_type = qspi
board_build.arduino.memory_type = qio_qspi 
board_build.partitions = partitions4.csv
upload_protocol = esptool
upload_port = COM9
monitor_port = COM9  ; Or /dev/ttyUSB0 for Linux/Mac
monitor_speed = 115200
;upload_protocol = espota
;upload_port = deskradio.local
;upload_flags =
;	--auth=admin
;monitor_port = socket://deskradio.local:4444
build_flags = 
	-Wall
	-Wextra
	-DCORE_DEBUG_LEVEL=4
    ;-DCONFIG_ARDUHAL_LOG_COLORS=1
	-DBOARD_HAS_PSRAM
	-DARDUINO_RUNNING_CORE=1
	-DARDUINO_EVENT_RUNNING_CORE=1
	-DPHILIPS=1
lib_deps = 
	https://github.com/yellobyte/SoapESP32.git#1.1.4
	;https://github.com/pschatzmann/ESP32-A2DP#v.1.8.1
	;https://github.com/pschatzmann/arduino-audio-tools.git#v0.9.8


[platformio]
description = ESP32 Unified Radio
